### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by jwinarske** [felipeerias/flutter_homescreen#2]
I have to remove reference to this project from [MR](https://gerrit.automotivelinux.org/gerrit/c/AGL/meta-agl-devel/+/26868) meta-agl-flutter recipe due to missing license.

AGL prefers Apache-2.0.

**Comment by felipeerias** [comment]
Thank you @jwinarske I have added the Apache 2.0 license to the project.

Fixed by PR https://github.com/felipeerias/flutter_homescreen/pull/3
